services:
  llm-gateway:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: llm-gateway
    restart: unless-stopped
    env_file: .env
    # ports:
    #   - "127.0.0.1:8002:8002"
    networks:
      - erp-network

  ollama:
    image: alpine/ollama:latest
    container_name: ollama
    restart: unless-stopped
    # ports:
    #   - "127.0.0.1:11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - erp-network

volumes:
  ollama_data:

networks:
  erp-network:
    external: true