services:
  llm-gateway:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: llm-gateway
    restart: unless-stopped
    env_file: .env
    ports:
      - "8002:8002"
    networks:
      - erp-network

networks:
  erp-network:
    external: true